Repository haru960197/BlackVocs, pull requests merged in 2025-10, with the labels that each got.

#119 Feature/118/review ai generation schema
  service/app/models/common.py
  service/app/routes/word.py
  service/app/schemas/word_schemas.py
  service/app/services/generativeAI_service.py
Labels: enhancement

#121 :recycle: apiのpromptをenvへ移動
  service/app/core/config.py
  service/app/services/generativeAI_service.py
Labels: refactor

#123 :+1: promptのupdateに伴う変更
  service/app/services/generativeAI_service.py
Labels: enhancement

#129 💚 Update .env.example
  service/.env.example
  web/.env.example
Labels: documentation

#132 :recycle: ディレクトリ名変更に伴い，不要になった古いファイルを削除
  web/src/components/SignupForm/SignUpForm.tsx
  web/src/components/SignupForm/action.ts
  web/src/components/SignupForm/index.ts
  web/src/components/SignupForm/schema.ts
Labels: bug

#133 👍 削除ボタンを追加
  web/src/components/WordList/WordListItem.tsx
  web/src/components/WordList/action.ts
Labels: enhancement
