Repository haru960197/BlackVocs, pull requests merged in 2025-09, with the labels that each got.

#88 :+1: service/delete機能の追加
  .gitignore
  service/app/repositories/user_word_repository.py
  service/app/repositories/word_repository.py
  service/app/routes/word.py
  service/app/schemas/word_schemas.py
  service/app/services/word_service.py
Labels: refactor

#96 ✨ READMEに開発手順を記載
  README.md
Labels: documentation

#97 :+1: docker立ち上げ必要性の追加
  README.md
Labels: documentation

#100 :bug: 新規登録画面でのエラーを解消
  web/src/components/SignupForm/SignUpForm.tsx
  web/src/components/SignupForm/index.ts
Labels: bug

#106 :label: モデルのtypeの変更
  service/app/models/common.py
  service/app/models/user.py
  service/app/models/user_word.py
  service/app/models/word.py
Labels: enhancement, refactor

#113 Fix/107/adjust to db models
  README.md
  service/app/core/jwt_auth.py
  service/app/models/common.py
  service/app/models/user_word.py
  service/app/models/word.py
  service/app/repositories/user_repository.py
  service/app/repositories/user_word_repository.py
  service/app/repositories/word_repository.py
  service/app/routes/auth.py
  service/app/routes/word.py
  service/app/schemas/auth_schemas.py
  service/app/schemas/word_schemas.py
  service/app/services/auth_service.py
  service/app/services/generativeAI_service.py
  service/app/services/word_service.py
  web/src/components/SignupForm/SignUpForm.tsx
  web/src/components/SignupForm/index.ts
Labels: refactor
